# 使用Python官方的镜像作为基础镜像
FROM python:3.10-slim

# 将工作目录设置为/app
WORKDIR /app


# 安装cron和ca && pip 安装依赖
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates cron && pip install requests pyyaml

# 将当前目录(app/python)下的所有文件复制到容器的/app目录下
COPY dukou /app/python/dukou
COPY logger /app/python/logger

ENV PYTHONPATH "/app/python"

# 添加crontab文件
RUN touch /app/python/checkin.sh &&  \
    touch /etc/cron.d/dukou-checkin-cron &&  \
    echo "PYTHONPATH=/app/python /usr/local/bin/python /app/python/dukou/checkin.py >> /var/log/cron.log 2>&1" > /app/python/checkin.sh &&  \
    echo "0 8 * * * root /app/python/checkin.sh" > /etc/cron.d/dukou-checkin-cron &&  \
    chmod 0644 /app/python/dukou/checkin.py && \
    chmod +x /app/python/checkin.sh && \
    chmod 0644 /etc/cron.d/dukou-checkin-cron && \
    touch /var/log/cron.log && \
    rm -rf /etc/localtime && \
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 启动容器立即执行一次，并启动cron 并打印日志
CMD ["sh","-c", "/app/python/checkin.sh  && cron && tail -f /var/log/cron.log"]
