# 使用Python官方的镜像作为基础镜像
FROM python:3.10-slim

# 将工作目录设置为/app
WORKDIR /app


# 安装ca && pip 安装依赖
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && pip install requests pyyaml
# RUN pip install -r requirements.txt

# 将当前目录(app/python)下的所有文件复制到容器的/app目录下
COPY dukou /app/python/dukou
COPY logger /app/python/logger

ENV PYTHONPATH "/app/python"
# 运行Python程序
CMD ["python", "/app/python/dukou/checkin.py"]